### ISSUE TITLE
Tweaks : wrap tables option miss up the database

### ISSUE THREAD

**Issue by Rhygaer** [notion-enhancer/extension#12]
**What is happening?**

- Tweaks: wrap tables to page width option [on] squashes all databases columns widths together,
- adding RTL support module [on] : will displace the database to right, leaving big gap on the left

**What should be happening?**
turning on the option should fit database width to page selected width, keeping position, and columns original size

**Screenshots (if applicable):**

[Firefox ](https://i.postimg.cc/hvjCSg2k/firefox.png)
[Brave ](https://i.postimg.cc/1tMCh4r0/Brave.png)

**Operating system/browser name & version:**

-  Windows 10 21H2 |  Firefox 98.0b2 (64-bit)
-  Windows 10 21H2 | Brave v. 1.35.100 Chromium: 98.0.4758.87 

**notion-enhancer and/or notion-repackaged version:**
-  Firefox extension  v0.11.0.1
-  Brave Chrome Extension 0.11.0.1

**notion-enhancer configuration (enabled/disabled mods and their settings):**

- None

AND/OR:
- Tweaks: ON
- RTL : ON

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/repo/issues/44
