### ISSUE TITLE
Collapsible Headers not working

### ISSUE THREAD

**Issue by Rhygaer** [notion-enhancer/extension#13]
**What is happening?**

- collapsible headers activation has no effect, they don't show
- or .. they stutter, closing and opening on their own very fast
- or .. jump their position up or down a bit on screen when scrolling
- or ..  close and open randomly when scrolling

**What should be happening?**
collapsible headers should show toggle triangle, respect position and state

**Screenshots (if applicable):**

**Operating system/browser name & version:**

-  Windows 10 21H2 |  Firefox 98.0b2 (64-bit)
-  Windows 10 21H2 | Brave v. 1.35.100 Chromium: 98.0.4758.87 

**notion-enhancer and/or notion-repackaged version:**
-  Firefox extension  v0.11.0.1
-  Brave Chrome Extension 0.11.0.1

**notion-enhancer configuration (enabled/disabled mods and their settings):**

- None

AND/OR:
- collapsible headers : ON

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/854, this feature is deprecated and soon to be removed
