### ISSUE TITLE
Cover photo BG color doesn't change with changed theme

### ISSUE THREAD

**Issue by Rhygaer** [notion-enhancer/extension#14]
**What is happening?**

- Cover photo BG color AND Database Entry page top Properties section don't color change with changed theme, both dark and light themes

**What should be happening?**
Cover photo BG AND DB Properties BG color corresponds to theme color

**Screenshots (if applicable):**

[Dark Theme ](https://i.postimg.cc/2y0JrFgT/2022-02-09-21-18-56-Window.png)
[Light Theme ](https://i.postimg.cc/BZpRT4tD/2022-02-09-21-20-45-Window.png)
**Operating system/browser name & version:**

-  Windows 10 21H2 |  Firefox 98.0b2 (64-bit)
-  Windows 10 21H2 | Brave v. 1.35.100 Chromium: 98.0.4758.87 

**notion-enhancer and/or notion-repackaged version:**
-  Firefox extension  v0.11.0.1
-  Brave Chrome Extension 0.11.0.1

**notion-enhancer configuration (enabled/disabled mods and their settings):**

- None

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/892 and in the wrong repo

please read the [contributing guide](https://notion-enhancer.github.io/about/contributing/) and check existing issues before opening an issue
