### ISSUE TITLE
Extension Not Working with Signed in account

### ISSUE THREAD

**Issue by behrooztahmasbi** [notion-enhancer/extension#3]
Hi
In my chrome extension of R to L Notion
R to L feature, while I'm signed in Not Working!!! ... But in Signed Out States (Like incognito) its fin

**Comment by dragonwocky** [comment]
hi, this bug report is in the wrong place & doesn't contain enough information for me to help you.
please read the contributing guidelines and then try again: https://notion-enhancer.github.io/about/contributing/
