### ISSUE TITLE
problemas with the colors themes

### ISSUE THREAD

**Issue by matheusfcw** [notion-enhancer/extension#4]
![image](https://user-images.githubusercontent.com/87440512/148274621-0a0f8e75-e664-4da3-a753-df95c1cbf2a5.png)

**Comment by dragonwocky** [comment]
duplicate of https://github.com/notion-enhancer/notion-enhancer/issues/892 and the template was not properly filled out

please follow the [contributing guidelines](https://notion-enhancer.github.io/about/contributing/) or your bug reports / feature requests will be closed
