### ISSUE TITLE
Large negative space under cover image

### ISSUE THREAD

**Issue by salamijason** [notion-enhancer/extension#7]
There's this large chunk of just nothing right under the cover image when I have themes enabled.
![image](https://user-images.githubusercontent.com/90419732/149859586-41029f95-a5ce-4722-9b4b-1240583cf944.png)

The size of this box differs from page to page.
![image](https://user-images.githubusercontent.com/90419732/149859693-a6796806-9842-44a4-8b75-fccd4f7e7f13.png)

This issue came up a few days ago. I have no idea what's causing it. It's there in both light and dark mode. After some testing, I found that this issue occurs with every light and dark theme available. 

Browser: Opera GX
Version of enhancer: notion-enhancer v0.11.0.1

**Comment by dragonwocky** [comment]
I think this is a dup of https://github.com/notion-enhancer/notion-enhancer/issues/892
If I've misunderstood you please reopen this issue and try and re-explain the problem to me
